---
  - name: Ensure nfs installed
    yum: name=nfs-utils state=latest
    become: true
    notify: restart nfs

  - name: Ensure directories to export exists
    file: 'path="{{ item.strip().split()[0] }}" state=directory'
    with_items: "{{ nfs.exports }}"
    become: true

  - name: Copy exports file
    template:
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
    become: true
    notify: restart nfs

  - meta: flush_handlers

  - name: Ensure remotefs install directory exists
    file: path=/home/core/remotefs state=directory

  - name: Install remotefs service
    copy: src=docker-compose-remotefs.yml dest=/home/core/remotefs/docker-compose.yml
    notify: restart remotefs
