---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - include: openstack/create-os-port.yml
    - include: openstack/create-os-server.yml
    - name: Wait for instance to come online
      wait_for:
        port: 22
        host: "{{ port_config.ip_address }}"
        delay: 5
        timeout: 600
    - name: Add server to inventory
      add_host:
        name: node
        groups: nodes
        ansible_host: "{{ port_config.ip_address }}"

  handlers:
    - include: handlers/common.yml

- hosts: node
  remote_user: core
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - include: docker/configure-docker.yml
    - include: compute-node/configure-compute-node.yml

  handlers:
    - include: handlers/common.yml
