---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - include: openstack/create-os-port.yml
    - include: openstack/create-os-server.yml
    - name: Wait for instance to come online
      wait_for:
        port: 22
        host: "{{ port_config.ip_address }}"
        delay: 5
        timeout: 600
    - name: Add nfs-server to inventory
      add_host:
        name: nfs-server
        groups: nfs-servers
        ansible_host: "{{ port_config.ip_address }}"

  handlers:
    - include: handlers/common.yml

- hosts: nfs-server
  remote_user: core
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - include: docker/configure-docker.yml
    - include: nfs/configure-nfs.yml

  handlers:
    - include: handlers/common.yml
