---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  roles:
    - vmware

  tasks:
    - name: Wait for instance to come online
      wait_for:
        port: 22
        host: "{{ item.appIP }}"
        delay: 5
        timeout: 600
      with_items:
       - storageNodes
    - name: Add nfs-server to inventory
      add_host:
        name: nfs-server
        groups: nfs-servers
        ansible_host: "{{ port_config.ip_address }}"

- hosts: nfs-servers
  remote_user: core
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  roles:
    - bootstrap-coreos
    - docker
    - nfs
