---
  - name: restart docker
    shell: systemctl daemon-reload && systemctl restart docker
    become: true

  - name: restart nfs
    service: name=nfs-server state=restarted
    become: true
    when: nfs.exports|length

  - name: restart remotefs
    shell: docker-compose -f {{ remotefs.data_dir }}/docker-compose.yml down && docker-compose -f {{ remotefs.data_dir }}/docker-compose.yml up -d

  - name: restart etcd
    shell: docker-compose -f {{ etcd.data_dir }}/docker-compose.yml down && docker-compose -f {{ etcd.data_dir }}/docker-compose.yml up -d

  - name: restart dns
    shell: docker-compose -f {{ dns.data_dir }}/docker-compose.yml down && docker-compose -f {{ dns.data_dir }}/docker-compose.yml up -d

  - name: restart dhcpd
    shell: docker-compose -f {{ dhcpd.data_dir }}/docker-compose.yml down && docker-compose -f {{ dhcpd.data_dir }}/docker-compose.yml up -d

  - name: restart plumber
    systemd:
      name: plumber
      enabled: yes
      daemon_reload: yes
      state: restarted
    become: true

  - name: restart dashboard agent
    systemd:
      name: infra-dashboard-agent
      enabled: yes
      daemon_reload: yes
      state: restarted
    become: true

  - name: restart dashboard publisher
    systemd:
      name: infra-dashboard-publisher
      enabled: yes
      daemon_reload: yes
      state: restarted
    become: true

  - name: restart logspout
    systemd:
      name: logspout
      enabled: yes
      daemon_reload: yes
      state: restarted
    become: true

  - name: restart dnsreg
    systemd:
      name: dnsreg
      enabled: yes
      daemon_reload: yes
      state: restarted
    become: true
